### ISSUE TITLE
How to test ?

### ISSUE THREAD

**Issue by szh91** [zhongyingji/APNet#3]
If I want to use for testing other datasets, how to do it?

**Comment by zhongyingji** [comment]
1. Make sure you've implemented the dataset and placed it in maskrcnn/data/datasets/yourdataset.py (the implementation is referred to prw_dataset.py), remember to modify maskrcnn_benchmark/data/datasets/__init__.py
2. Add the relevant path and the parameters into maskrcnn_benchmark/config/paths_catalog.py
3. suppose you've trained an OIM on PRW, e.g.,  models/OIM, 
modify configs/reid/PRW_R_50_C4.yaml:
DATASETS:
    TRAIN: ("your_dataset_train", )
    TEST: ("your_dataset_test", "your_dataset_query", )

run:
python tools/train_net.py --config-file "configs/reid/prw_R_50_C4.yaml"  OUTPUT_DIR "models/OIM"
