### ISSUE TITLE
Image size for CUHK-SYSU and PRW

### ISSUE THREAD

**Issue by munjalbharti** [zhongyingji/APNet#5]
Dear author,
Can you please tell which image size you used for CUHK-SYSU and PRW dataset? 

The previous work QEEPS rescales the images such that the shorter side is 900 pixels. 
https://github.com/munjalbharti/Query-guided-End-to-End-Person-Search.

In your paper the image size is not mentioned. Can you please tell the image size used?

Thank you
Bharti Munjal

**Comment by zhongyingji** [comment]
We use 1500x900 for both dataset.
